cancers = [
    "breast cancer",
    "lung cancer",
    "prostate cancer",
    "colorectal cancer",
    "colon cancer",
    "bowel cancer",
    "melanoma",
    "skin cancer",
    "bladder cancer",
    "non-hodgkin lymphoma",
    "kidney cancer",
    "renal cancer",
    "endometrial cancer",
    "uterine cancer",
    "leukemia",
    "pancreatic cancer",
    "thyroid cancer",
    "liver cancer",
    "hepatic cancer",
    "brain tumor",
    "brain cancer",
    "ovarian cancer",
    "cervical cancer",
    "stomach cancer",
    "gastric cancer",
    "esophageal cancer",
    "gallbladder cancer",
    "testicular cancer",
    "bone cancer",
    "osteosarcoma",
    "sarcoma",
    "multiple myeloma",
    "hodgkin lymphoma",
    "throat cancer",
    "laryngeal cancer",
    "oral cancer",
    "mouth cancer",
    "mesothelioma",
    "neuroblastoma",
    "retinoblastoma",
    "vulvar cancer",
    "vaginal cancer",
    "anal cancer",
    "penile cancer",
    "bile duct cancer",
    "adrenal cancer",
    "pituitary tumor",
    "spinal cord tumor"
]

for c in cancers:
    print(c)
